baseurl = ""
languageCode = "en-us"
title = "Louielyn Panganiban Resume"
theme = "hugo-orbit-theme"
googleAnalytics = "UA-XXXXXXX-Y"

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "Hugo Responsive Resume/CV Theme for Developers"
    author = "Daryl Galvez"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # itâ€™s quick and easy to change the styling and colour scheme.

    styles = "styles-2.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Maria Louielyn Panganiban"
        tagline = "Doctor of Dental Medicine"
        avatar = "fblou1.jpg.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: louielyn.pananiban@gmail.com"
        title = "louielyn.panganiban@gmail.com"

        # [[params.contact.list]]
        # class = "phone"
        # icon = "fa-phone"
        # url = "tel:+1234567890"
        # title = "+1234567890"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//luxesmilesdentalcenter.com"
        title = "luxesmilesdentalcenter.com"

        [[params.contact.list]]
        class = "website"
        icon = "fa-globe"
        url = "//luxesmilesdentalcenter.netlify.app"
        title = "luxesmilesdentalcenter.netlify.app"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/louiepanganiban"
        title = "linkedin.com/in/louiepanganiban"

        # [[params.contact.list]]
        # class = "github"
        # icon = "fa-github"
        # url = "//github.com/username"
        # title = "github.com/username"

        # [[params.contact.list]]
        # class = "twitter"
        # icon = "fa-twitter"
        # url = "//twitter.com/username"
        # title = "@twittername"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Doctor of Dental Medicine"
        college = "University of the Philippines - Manila"
        dates = "2007 - 2013"

        [[params.education.list]]
        degree = "High School Diploma"
        college = "Bristol Manila Central University"
        dates = "2002 - 2007"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "Filipino - Tagalog"
        level = "Native"

        [[params.language.list]]
        language = "English"
        level = "Professional"

        # [[params.language.list]]
        # language = "Russian"
        # level = "Professional"

    # Interests section
    [params.interests]
        enable = true
        title = "Interests"

        [[params.interests.list]]
        interest = "Cycling"

        [[params.interests.list]]
        interest = "Cooking"

        [[params.interests.list]]
        interest = "Photography"

# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)

    # Summary section
    [params.summary]
        enable = true
        icon = "fa-user"
        title = "Career Profile"
        summary = """**I am a dentist** and I provide my patients with professional dental care which
                    stems from my years of education and practical training obtained from my university
                    and from various seminars and lectures. I am well versed with various dental procedures
                    ranging from restorative, prosthodontic, endodontic, and periodontic procedures. I have
                    also received training for oral surgery, management of immune-compromised patients, TMJ
                    pain management, and orthodontics."""

    # Experiences section
    [params.experiences]
        enable = true
        icon = "fa-briefcase"
        title = "Experiences"

        [[params.jobs.list]]
        position = "Dental Consultant"
        dates = "2018 - Present"
        company = "Dain Dental Clinic"
        # details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo.\n\n Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo."

        [[params.jobs.list]]
        position = "Dentist/ Owner"
        dates = "2016 - Present"
        company = "Luxe Smiles Dental Center"
        # details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem. Nulla consequat massa quis enim. Donec pede justo.\n\n Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo."

        [[params.jobs.list]]
        position = "Head Dentist/ Owner"
        dates = "2014 - Present"
        company = "Panganiban Dental Clinic"
        # details = "**Describe your role here** lorem ipsum dolor sit amet, consectetuer adipiscing elit. Aenean commodo ligula eget dolor. Aenean massa. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Donec quam felis, ultricies nec, pellentesque eu, pretium quis, sem."

        [[params.jobs.list]]
        position = "Professor and Clinical Instructor"
        dates = "2015 - 2020"
        company = "Centro Escolar University - Manila"
        details = "Faculty member in Department of Endodontics, Department of Periodontics, Department of Prosthodontics, and Department of Surgery"

    # Projects section
    [params.projects]
        enable = true
        icon = "fa-archive"
        title = "Training and Seminars"
        # intro = "**You can list your side projects or open source libraries in this section.** Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum et ligula in nunc bibendum fringilla a eu lectus"

        [[params.projects.list]]
        title = "Externship Training Program in Oral Surgery"
        url = "https://github.com/aerohub/hugrid"
        tagline = "Grid theme for Hugo. It's a kind of boilerplate to perform anyone or anything quickly. Portfolio, collection, bookmarks, contacts and so on"

        [[params.projects.list]]
        title = "Simple FAQ Theme for Hugo"
        url = "https://github.com/aerohub/hugo-faq-theme"
        tagline = "Simple FAQ Theme for Hugo. You may use this theme for building very simple FAQs or note lists."

        [[params.projects.list]]
        title = "Hugo Identity"
        url = "https://github.com/aerohub/hugo-identity-theme"
        tagline = "Little profile/card-style template for Hugo."

        [[params.projects.list]]
        title = "Orbit"
        url = "https://github.com/aerohub/hugo-orbit-theme"
        tagline = "Hugo Resume/CV Theme for Developers."

        [[params.projects.list]]
        title = "Me"
        url = "https://github.com/aerohub/hugo-me-theme"
        tagline = "A simple responsive Hugo theme for personal site."

    # Skills section
    [params.skills]
        enable = true
        icon = "fa-rocket"
        title = "Skills & Proficiency"

        [[params.skills.list]]
        skill = "Oral Surgery"
        level = "98%"

        [[params.skills.list]]
        skill = "Orthodontics"
        level = "98%"

        [[params.skills.list]]
        skill = "Hospital and Clinic Management"
        level = "95%"

        [[params.skills.list]]
        skill = "Temporary Anchorage Devices"
        level = "95%"

        [[params.skills.list]]
        skill = "TMJ Pain Management"
        level = "95%"

        [[params.skills.list]]
        skill = "Photography and Editing"
        level = "80%"

    # Footer section

    # The original template is released under the Creative Commons Attribution 3.0 License.
    # Please keep the original attribution link when using for your own project.
    # If you'd like to use the template without the attribution,
    # you can check out other license options via template author's website: themes.3rdwavemedia.com
    #
    # As for Hugo port you may rewrite the "Ported for..." line with setting your name below.

    [params.footer]
        copyright = ""
